[package]
name = "clib"
version = "0.1.0"
authors = ["jtschuster <jacksontschuster@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "clib"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
